
image: node:lts-bullseye

.buildenv:
  before_script:
    - apt update -y && apt -y install s3cmd python3-pip
    - pip3 install -U platformio
    - echo "host_base = s3.womolin.de" > ~/.s3cfg
    - echo "host_bucket = s3.womolin.de" >> ~/.s3cfg
    - echo "bucket_location = de-fra" >> ~/.s3cfg
    - echo "use_https = True" >> ~/.s3cfg
    - echo "access_key = $S3_ACCESS_KEY" >> ~/.s3cfg
    - echo "secret_key = $S3_SECRET_KEY" >> ~/.s3cfg
    - echo "signature_v2 = False" >> ~/.s3cfg
    - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
    - npm config set "//npm.fontawesome.com/:_authToken" "$NPM_FONTAWESOME_KEY"

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache
    - .pio
    - ui/node_modules

stages:
 - build
 - upload

build-webui:
  stage: build
  extends: .buildenv
  dependencies: []
  needs: []
  artifacts:
    paths:
      - $BUILD_DIR/.pio/build/wemos_d1_mini32/littlefs.bin
  script:
    - cd ui
    - npm install
    - npm run build
    - cd ..
    - pio run -e wemos_d1_mini32 -t buildfs

build-firmware:
  stage: build
  extends: .buildenv
  dependencies: []
  needs: []
  artifacts:
    paths:
      - $BUILD_DIR/current-version.json
      - $BUILD_DIR/.pio/build/wemos_d1_mini32/firmware.bin
      - $BUILD_DIR/.pio/build/wemos_d1_mini32/partitions.bin
      - ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/bin/bootloader_dio_80m.bin
      - ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin
  script:
    - pio run -e wemos_d1_mini32

upload:
  stage: upload
  extends: .buildenv
  dependencies:
    - build-firmware
    - build-webui
  needs:
    - build-firmware
    - build-webui
  script:
    - s3cmd put current-version.json s3://webinstaller/gaslevel-latest/
    - s3cmd put .pio/build/wemos_d1_mini32/firmware.bin s3://webinstaller/gaslevel-latest/
    - s3cmd put .pio/build/wemos_d1_mini32/littlefs.bin s3://webinstaller/gaslevel-latest/
    - s3cmd put .pio/build/wemos_d1_mini32/partitions.bin s3://webinstaller/gaslevel-latest/
    - s3cmd put ~/.platformio/packages/framework-arduinoespressif32/tools/sdk/esp32/bin/bootloader_dio_80m.bin s3://webinstaller/gaslevel-latest/
    - s3cmd put ~/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin s3://webinstaller/gaslevel-latest/
