name: Create Firmware

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Installing platformio
      run: pip3 install -U platformio

    - name: Building a firmware for ESP32
      run: |
        pio run
        pio run -t buildfs
# produces ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin
# produces ${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin

    - name: 'Upload firmware Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: |
          ${{ github.workspace }}/.pio/build/esp32dev/firmware.bin

    - name: 'Upload spiffs Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: spiffs.bin
        path: |
          ${{ github.workspace }}/.pio/build/esp32dev/spiffs.bin
